# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]

jobs:
  release-artifacts:
#    needs:
#      - release-prerequisites
#      - golang-build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: thetillhoff/action-goreportcard-refresh@v1.0.1
